name: Run model

on: 
  push:
    branches: ['main']

jobs:
  train_model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Możesz określić konkretną
      
      - name: Install dependencies
        run: pip install -r requirements.txt 

      - name: Run load_data.py
        run: python src/load_data.py

      - name: Run train.py
        env:
          MLFLOW_TRACKING_URI: 'https://2298-34-80-142-9.ngrok-free.app'
        run: python src/train.py

  test_load_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Możesz określić konkretną
      
      - name: Install dependencies
        run: pip install -r requirements.txt 

      - name: Run test_load_data.py
        run: python tests/test_load_data.py
  